'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property VaultConnectionName() As String
            Get
                Return CType(Me("VaultConnectionName"),String)
            End Get
            Set
                Me("VaultConnectionName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TemplateColumnCollection() As Global.ExcitechDOCS.Settings.ColumnCollection
            Get
                Return CType(Me("TemplateColumnCollection"),Global.ExcitechDOCS.Settings.ColumnCollection)
            End Get
            Set
                Me("TemplateColumnCollection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UpdateReferenceWindowPlacement() As Global.ExcitechDOCS.Settings.WindowPlacement
            Get
                Return CType(Me("UpdateReferenceWindowPlacement"),Global.ExcitechDOCS.Settings.WindowPlacement)
            End Get
            Set
                Me("UpdateReferenceWindowPlacement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UpdateReferenceColumnCollection() As Global.ExcitechDOCS.Settings.ColumnCollection
            Get
                Return CType(Me("UpdateReferenceColumnCollection"),Global.ExcitechDOCS.Settings.ColumnCollection)
            End Get
            Set
                Me("UpdateReferenceColumnCollection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ReopenDrawingAfterWorkflowTransition() As Boolean
            Get
                Return CType(Me("ReopenDrawingAfterWorkflowTransition"),Boolean)
            End Get
            Set
                Me("ReopenDrawingAfterWorkflowTransition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TemplateSearchTerm() As String
            Get
                Return CType(Me("TemplateSearchTerm"),String)
            End Get
            Set
                Me("TemplateSearchTerm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TemplateWindowPlacement() As Global.ExcitechDOCS.Settings.WindowPlacement
            Get
                Return CType(Me("TemplateWindowPlacement"),Global.ExcitechDOCS.Settings.WindowPlacement)
            End Get
            Set
                Me("TemplateWindowPlacement") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ExcitechDOCS_AutoCAD_Addin.My.MySettings
            Get
                Return Global.ExcitechDOCS_AutoCAD_Addin.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
